name: Deploy to Test

on:
  pull_request:

jobs:
  deploy-test:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          port: ${{secrets.SSH_PORT}}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            echo $BRANCH
            cd /srv/app/test
            git pull origin $BRANCH
            git checkout $BRANCH
            npm install
            supervisorctl restart app
    env:
      BRANCH: ${{github.payload.pull_request.head.ref}}
