name: Deploy to Test

on:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo running on branch ${github.payload.pull_request.head.ref }
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          port: ${{secrets.SSH_PORT}}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /srv/app/test
            git pull origin {github.payload.pull_request.head.ref }
            npm install
            supervisorctl restart app